### ISSUE TITLE
odd trip_no in 2019 data

### ISSUE THREAD

**Issue by jysullivan** [commfish/seak_sablefish#40]
Sent to M Vaughn 2019-12-19:

1)	the A/B trip numbers for 113 and 144. I don’t have any records of A/B trips for other years. This will break a lot of code… Is there a good reason to have these separate? If so, why not assign them separate trip nos?
2)	Trip 136 with 6 lb? Seems odd.

**Comment by jysullivan** [comment]
Follow up:

These were labelled as A and B because the first part of the trip was landed at a tender but the second part was landed shoreside. They have the same log book but different fish tickets.

... in the interim I'm going to hard code these as trips 113/114 and 144/145 until Rhea E and I can come up with a better solution

**Comment by rhea-adfg** [comment]
This is becoming more common with permit holders delivering mid-trip to a tender so we will have to establish a protocol. From the fish ticket side of things, these are "partial deliveries" and must be considered as one trip due to calculating bycatch allowances. From the logbook side, harvest on the logbook doesn't necessarily match with harvest on the fish ticket if they only offload part of their delivery to the tender. If you combine the logbooks and tickets from the partial deliveries to make it one trip, everything is accounted for appropriately. But then that leaves the issue of how to deal with samples of the partial deliveries, assigning tags, and entering biological samples for two or more partial deliveries.

**Comment by jysullivan** [comment]
Use 9000 series per [https://github.com/commfish/seak_sablefish/blob/ea0ef5821cc7de25a45639b4183ae772dfd948b7/r/mark_recapture.R#L609](url)

**Comment by rhea-adfg** [comment]
Would you combine countback info into one trip then? I'm not sure how to use the 9000 series if we still have two partial trips with two different countbacks and bio samples. We can do this for the Cape Enchantment that had one sample for two landings, but I don't know how to do it for the other boat that had two separate countbacks and bio samples from two partial deliveries.

**Comment by jysullivan** [comment]
@rhea-adfg  my thought is that the 9000 series could capture the "partial" nature of a trip.

For example, the first part of a trip comes in as trip 113. It has a fish ticket, bio samples, and countback data associated with 113. The second part of the trip would come in as 9113. It could also have bio samples and countback data associated with 9113, but the fish ticket and logbook would be 113 because it's part of the original trip. The 9 would alert an analyst that this is a partial trip that is linked to another fish ticket and logbook.

**Comment by jysullivan** [comment]
@rhea-adfg is going to create separate trips for 113/114 and 144/145 for the following data:
- countbacks
- bio data
- tag data
- countbacks
- logbooks

**Comment by rhea-adfg** [comment]
Trip 113 A and B were split into Trip 113 and 114, respectively. 
Trip 144 A and B were split into Trip 144 and 145, respectively. 

To do this, I had to update the countback spreadsheet, fish tickets, logbooks, biological data, and tags accordingly.  Data for Chatham will probably have to be re-output since trip numbers and set numbers have changed in logbooks/tag data, and specimen numbers have changed in the biological samples.

**Comment by jysullivan** [comment]
Resolved, and data has been updated:
![image](https://user-images.githubusercontent.com/7398155/73110480-07412780-3eb3-11ea-883c-4ad63573c86c.png)
